\c games_db;

CREATE USER games_db_r WITH PASSWORD 'password';
GRANT CONNECT ON DATABASE games_db TO games_db_r;
GRANT USAGE ON SCHEMA public TO games_db_r;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO games_db_r;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO games_db_r;